export const featureDataMock = {
    layers: [
        {
            id: 0,
            objectIdFieldName: 'OBJECTID',
            globalIdFieldName: '',
            geometryType: 'esriGeometryPoint',
            spatialReference: {
                wkid: 4326,
                latestWkid: 4326,
            },
            fields: [
                {
                    name: 'OBJECTID',
                    type: 'esriFieldTypeOID',
                    alias: 'OBJECTID',
                    sqlType: 'sqlTypeOther',
                    domain: null,
                    defaultValue: null,
                },
                {
                    name: 'OBJECTID',
                    type: 'type',
                    alias: 'duplikaatti',
                    sqlType: 'sqlTypeOther',
                    domain: null,
                    defaultValue: null,
                },
                {
                    name: 'CITY_FIPS',
                    type: 'esriFieldTypeString',
                    alias: 'CITY_FIPS',
                    sqlType: 'sqlTypeOther',
                    length: 5,
                    domain: null,
                    defaultValue: null,
                },
                {
                    name: 'CITY_NAME',
                    type: 'esriFieldTypeString',
                    alias: 'CITY_NAME',
                    sqlType: 'sqlTypeOther',
                    length: 40,
                    domain: null,
                    defaultValue: null,
                },
                {
                    name: 'STATE_FIPS',
                    type: 'esriFieldTypeString',
                    alias: 'STATE_FIPS',
                    sqlType: 'sqlTypeOther',
                    length: 2,
                    domain: null,
                    defaultValue: null,
                },
                {
                    name: 'STATE_NAME',
                    type: 'esriFieldTypeString',
                    alias: 'STATE_NAME',
                    sqlType: 'sqlTypeOther',
                    length: 25,
                    domain: null,
                    defaultValue: null,
                },
                {
                    name: 'STATE_CITY',
                    type: 'esriFieldTypeString',
                    alias: 'STATE_CITY',
                    sqlType: 'sqlTypeOther',
                    length: 7,
                    domain: null,
                    defaultValue: null,
                },
                {
                    name: 'TYPE',
                    type: 'esriFieldTypeString',
                    alias: 'TYPE',
                    sqlType: 'sqlTypeOther',
                    length: 25,
                    domain: null,
                    defaultValue: null,
                },
                {
                    name: 'CAPITAL',
                    type: 'esriFieldTypeString',
                    alias: 'CAPITAL',
                    sqlType: 'sqlTypeOther',
                    length: 1,
                    domain: null,
                    defaultValue: null,
                },
                {
                    name: 'ELEVATION',
                    type: 'esriFieldTypeSmallInteger',
                    alias: 'ELEVATION',
                    sqlType: 'sqlTypeOther',
                    domain: null,
                    defaultValue: null,
                },
                {
                    name: 'POP1990',
                    type: 'esriFieldTypeInteger',
                    alias: 'POP1990',
                    sqlType: 'sqlTypeOther',
                    domain: null,
                    defaultValue: null,
                },
                {
                    name: 'HOUSEHOLDS',
                    type: 'esriFieldTypeInteger',
                    alias: 'HOUSEHOLDS',
                    sqlType: 'sqlTypeOther',
                    domain: null,
                    defaultValue: null,
                },
                {
                    name: 'MALES',
                    type: 'esriFieldTypeInteger',
                    alias: 'MALES',
                    sqlType: 'sqlTypeOther',
                    domain: null,
                    defaultValue: null,
                },
                {
                    name: 'FEMALES',
                    type: 'esriFieldTypeInteger',
                    alias: 'FEMALES',
                    sqlType: 'sqlTypeOther',
                    domain: null,
                    defaultValue: null,
                },
                {
                    name: 'GLOBALID',
                    type: 'esriFieldTypeGlobalID',
                    alias: 'GLOBALID',
                    sqlType: 'sqlTypeOther',
                    length: 38,
                    domain: null,
                    defaultValue: null,
                },
            ],
            features: [
                {
                    attributes: {
                        OBJECTID: 69,
                        CITY_FIPS: '66000',
                        CITY_NAME: 'San Diego',
                        STATE_FIPS: '06',
                        STATE_NAME: 'California',
                        STATE_CITY: '0666000',
                        TYPE: 'city',
                        CAPITAL: 'N',
                        ELEVATION: 42,
                        POP1990: 1110549,
                        HOUSEHOLDS: 406096,
                        MALES: 566464,
                        FEMALES: 544085,
                        GLOBALID: 'e2c94f46-17d3-4459-9675-600ae69f4d1f',
                    },
                    geometry:
                    {
                        x: -117.13666926135465,
                        y: 32.814997725516207,
                    },
                },
            ],
        },
    ],
};
