FROM python:3.7-slim-buster
ARG JENKINS_UID=1000
COPY ci/confs/pip* /etc/

RUN apt-get update && apt-get -y install xvfb chromium chromium-driver

RUN pip install --upgrade pip
RUN LIBRARY_PATH=/lib:/usr/lib /bin/sh -c "pip install -r /etc/pip-requirements.txt"

ENV DISPLAY=:99
ENV ENTRYPOINT Xvfb :99
RUN export DISPLAY=:99

RUN adduser -D -S -u ${JENKINS_UID} jenkins
RUN chown -R jenkins /home/jenkins

