FROM maven:3-jdk-8
ARG JENKINS_UID=1000
ENV TZ=EEST
RUN adduser --system --uid ${JENKINS_UID} jenkins
RUN mkdir /home/jenkins/.m2
COPY confs/settings.xml /home/jenkins/.m2/settings.xml
COPY confs/npmrc /home/jenkins/.npmrc
RUN chown -R jenkins /home/jenkins
