// flow-typed signature: f5b9f648ec29f1b5077b299498b315e3
// flow-typed version: <<STUB>>/babel-preset-airbnb_v^3.2.0/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-airbnb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-airbnb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-airbnb/index' {
  declare module.exports: $Exports<'babel-preset-airbnb'>;
}
declare module 'babel-preset-airbnb/index.js' {
  declare module.exports: $Exports<'babel-preset-airbnb'>;
}
