// flow-typed signature: 600ee2cc36cec3239e92d7d804129133
// flow-typed version: <<STUB>>/esri-loader_v2.12.0/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esri-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esri-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esri-loader/dist/esm/esri-loader' {
  declare module.exports: any;
}

declare module 'esri-loader/dist/esm/modules' {
  declare module.exports: any;
}

declare module 'esri-loader/dist/esm/script' {
  declare module.exports: any;
}

declare module 'esri-loader/dist/esm/utils/css' {
  declare module.exports: any;
}

declare module 'esri-loader/dist/esm/utils' {
  declare module.exports: any;
}

declare module 'esri-loader/dist/esm/utils/url' {
  declare module.exports: any;
}

declare module 'esri-loader/dist/umd/esri-loader' {
  declare module.exports: any;
}

declare module 'esri-loader/dist/umd/esri-loader.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esri-loader/dist/esm/esri-loader.js' {
  declare module.exports: $Exports<'esri-loader/dist/esm/esri-loader'>;
}
declare module 'esri-loader/dist/esm/modules.js' {
  declare module.exports: $Exports<'esri-loader/dist/esm/modules'>;
}
declare module 'esri-loader/dist/esm/script.js' {
  declare module.exports: $Exports<'esri-loader/dist/esm/script'>;
}
declare module 'esri-loader/dist/esm/utils/css.js' {
  declare module.exports: $Exports<'esri-loader/dist/esm/utils/css'>;
}
declare module 'esri-loader/dist/esm/utils/index' {
  declare module.exports: $Exports<'esri-loader/dist/esm/utils'>;
}
declare module 'esri-loader/dist/esm/utils/index.js' {
  declare module.exports: $Exports<'esri-loader/dist/esm/utils'>;
}
declare module 'esri-loader/dist/esm/utils/url.js' {
  declare module.exports: $Exports<'esri-loader/dist/esm/utils/url'>;
}
declare module 'esri-loader/dist/umd/esri-loader.js' {
  declare module.exports: $Exports<'esri-loader/dist/umd/esri-loader'>;
}
declare module 'esri-loader/dist/umd/esri-loader.min.js' {
  declare module.exports: $Exports<'esri-loader/dist/umd/esri-loader.min'>;
}
