// flow-typed signature: b54abf6681b1a27e5aa2db5d1489051c
// flow-typed version: <<STUB>>/esri-loader_v2.6.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esri-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esri-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esri-loader/dist/esm/esri-loader' {
  declare module.exports: any;
}

declare module 'esri-loader/dist/esm/utils/css' {
  declare module.exports: any;
}

declare module 'esri-loader/dist/umd/esri-loader' {
  declare module.exports: any;
}

declare module 'esri-loader/dist/umd/esri-loader.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esri-loader/dist/esm/esri-loader.js' {
  declare module.exports: $Exports<'esri-loader/dist/esm/esri-loader'>;
}
declare module 'esri-loader/dist/esm/utils/css.js' {
  declare module.exports: $Exports<'esri-loader/dist/esm/utils/css'>;
}
declare module 'esri-loader/dist/umd/esri-loader.js' {
  declare module.exports: $Exports<'esri-loader/dist/umd/esri-loader'>;
}
declare module 'esri-loader/dist/umd/esri-loader.min.js' {
  declare module.exports: $Exports<'esri-loader/dist/umd/esri-loader.min'>;
}
