// flow-typed signature: 30eb84c79b30db5113cc8873187dd737
// flow-typed version: <<STUB>>/jest-when_v^2.7.0/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-when'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-when' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-when/src/log' {
  declare module.exports: any;
}

declare module 'jest-when/src/log.test' {
  declare module.exports: any;
}

declare module 'jest-when/src/when' {
  declare module.exports: any;
}

declare module 'jest-when/src/when.test' {
  declare module.exports: any;
}

declare module 'jest-when/stryker.conf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-when/src/log.js' {
  declare module.exports: $Exports<'jest-when/src/log'>;
}
declare module 'jest-when/src/log.test.js' {
  declare module.exports: $Exports<'jest-when/src/log.test'>;
}
declare module 'jest-when/src/when.js' {
  declare module.exports: $Exports<'jest-when/src/when'>;
}
declare module 'jest-when/src/when.test.js' {
  declare module.exports: $Exports<'jest-when/src/when.test'>;
}
declare module 'jest-when/stryker.conf.js' {
  declare module.exports: $Exports<'jest-when/stryker.conf'>;
}
