// flow-typed signature: 0f24d0aa1b06b6f39e25974b1c57d225
// flow-typed version: <<STUB>>/nano-equal_v^2.0.2/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nano-equal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nano-equal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nano-equal/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nano-equal/src/index.js' {
  declare module.exports: $Exports<'nano-equal/src/index'>;
}
