// flow-typed signature: a2ce1bb5ed4f9210501c8391e9dcfc06
// flow-typed version: <<STUB>>/nano-equal_v^2.0.2/flow_v0.199.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nano-equal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nano-equal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nano-equal/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nano-equal/src/index' {
  declare module.exports: $Exports<'nano-equal/src'>;
}
declare module 'nano-equal/src/index.js' {
  declare module.exports: $Exports<'nano-equal/src'>;
}
