// flow-typed signature: bca83cdf059d198d2d0fd334d0fbca32
// flow-typed version: <<STUB>>/react-localization_v^1.0.13/flow_v0.199.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-localization'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-localization' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-localization/lib/LocalizedStrings' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-localization/lib/LocalizedStrings.js' {
  declare module.exports: $Exports<'react-localization/lib/LocalizedStrings'>;
}
