// flow-typed signature: eab1b9a533d97edd100577998024740f
// flow-typed version: <<STUB>>/react-spinners_v^0.13.7/flow_v0.199.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-spinners'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-spinners' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-spinners/BarLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/BeatLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/BounceLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/CircleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/BarLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/BeatLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/BounceLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/CircleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/ClimbingBoxLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/ClipLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/ClockLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/DotLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/FadeLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/GridLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/HashLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/helpers/animation' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/helpers/animation.server.test' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/helpers/animation.test' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/helpers/colors' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/helpers/colors.test' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/helpers/props' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/helpers/unitConverter' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/helpers/unitConverter.test' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/MoonLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/PacmanLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/PropagateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/PuffLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/PulseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/RingLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/RiseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/RotateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/ScaleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/SkewLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/SquareLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/SyncLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/ClimbingBoxLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/ClipLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/ClockLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/DotLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/BarLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/BeatLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/BounceLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/CircleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/ClimbingBoxLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/ClipLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/ClockLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/DotLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/FadeLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/GridLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/HashLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/helpers/animation' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/helpers/animation.server.test' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/helpers/animation.test' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/helpers/colors' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/helpers/colors.test' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/helpers/props' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/helpers/unitConverter' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/helpers/unitConverter.test' {
  declare module.exports: any;
}

declare module 'react-spinners/esm' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/MoonLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/PacmanLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/PropagateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/PuffLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/PulseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/RingLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/RiseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/RotateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/ScaleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/SkewLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/SquareLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/SyncLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/FadeLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/GridLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/HashLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/helpers/animation' {
  declare module.exports: any;
}

declare module 'react-spinners/helpers/animation.server.test' {
  declare module.exports: any;
}

declare module 'react-spinners/helpers/animation.test' {
  declare module.exports: any;
}

declare module 'react-spinners/helpers/colors' {
  declare module.exports: any;
}

declare module 'react-spinners/helpers/colors.test' {
  declare module.exports: any;
}

declare module 'react-spinners/helpers/props' {
  declare module.exports: any;
}

declare module 'react-spinners/helpers/unitConverter' {
  declare module.exports: any;
}

declare module 'react-spinners/helpers/unitConverter.test' {
  declare module.exports: any;
}

declare module 'react-spinners/MoonLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/PacmanLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/PropagateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/PuffLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/PulseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/RingLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/RiseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/RotateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/ScaleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/SkewLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/SquareLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/SyncLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/BarLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/BeatLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/BounceLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/CircleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/ClimbingBoxLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/ClipLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/ClockLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/DotLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/FadeLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/GridLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/HashLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/helpers/animation' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/helpers/animation.server.test' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/helpers/animation.test' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/helpers/colors' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/helpers/colors.test' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/helpers/props' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/helpers/unitConverter' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/helpers/unitConverter.test' {
  declare module.exports: any;
}

declare module 'react-spinners/umd' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/MoonLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/PacmanLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/PropagateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/PuffLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/PulseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/RingLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/RiseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/RotateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/ScaleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/SkewLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/SquareLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/SyncLoader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-spinners/BarLoader.js' {
  declare module.exports: $Exports<'react-spinners/BarLoader'>;
}
declare module 'react-spinners/BeatLoader.js' {
  declare module.exports: $Exports<'react-spinners/BeatLoader'>;
}
declare module 'react-spinners/BounceLoader.js' {
  declare module.exports: $Exports<'react-spinners/BounceLoader'>;
}
declare module 'react-spinners/CircleLoader.js' {
  declare module.exports: $Exports<'react-spinners/CircleLoader'>;
}
declare module 'react-spinners/cjs/BarLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/BarLoader'>;
}
declare module 'react-spinners/cjs/BeatLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/BeatLoader'>;
}
declare module 'react-spinners/cjs/BounceLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/BounceLoader'>;
}
declare module 'react-spinners/cjs/CircleLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/CircleLoader'>;
}
declare module 'react-spinners/cjs/ClimbingBoxLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/ClimbingBoxLoader'>;
}
declare module 'react-spinners/cjs/ClipLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/ClipLoader'>;
}
declare module 'react-spinners/cjs/ClockLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/ClockLoader'>;
}
declare module 'react-spinners/cjs/DotLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/DotLoader'>;
}
declare module 'react-spinners/cjs/FadeLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/FadeLoader'>;
}
declare module 'react-spinners/cjs/GridLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/GridLoader'>;
}
declare module 'react-spinners/cjs/HashLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/HashLoader'>;
}
declare module 'react-spinners/cjs/helpers/animation.js' {
  declare module.exports: $Exports<'react-spinners/cjs/helpers/animation'>;
}
declare module 'react-spinners/cjs/helpers/animation.server.test.js' {
  declare module.exports: $Exports<'react-spinners/cjs/helpers/animation.server.test'>;
}
declare module 'react-spinners/cjs/helpers/animation.test.js' {
  declare module.exports: $Exports<'react-spinners/cjs/helpers/animation.test'>;
}
declare module 'react-spinners/cjs/helpers/colors.js' {
  declare module.exports: $Exports<'react-spinners/cjs/helpers/colors'>;
}
declare module 'react-spinners/cjs/helpers/colors.test.js' {
  declare module.exports: $Exports<'react-spinners/cjs/helpers/colors.test'>;
}
declare module 'react-spinners/cjs/helpers/props.js' {
  declare module.exports: $Exports<'react-spinners/cjs/helpers/props'>;
}
declare module 'react-spinners/cjs/helpers/unitConverter.js' {
  declare module.exports: $Exports<'react-spinners/cjs/helpers/unitConverter'>;
}
declare module 'react-spinners/cjs/helpers/unitConverter.test.js' {
  declare module.exports: $Exports<'react-spinners/cjs/helpers/unitConverter.test'>;
}
declare module 'react-spinners/cjs/index' {
  declare module.exports: $Exports<'react-spinners/cjs'>;
}
declare module 'react-spinners/cjs/index.js' {
  declare module.exports: $Exports<'react-spinners/cjs'>;
}
declare module 'react-spinners/cjs/MoonLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/MoonLoader'>;
}
declare module 'react-spinners/cjs/PacmanLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/PacmanLoader'>;
}
declare module 'react-spinners/cjs/PropagateLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/PropagateLoader'>;
}
declare module 'react-spinners/cjs/PuffLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/PuffLoader'>;
}
declare module 'react-spinners/cjs/PulseLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/PulseLoader'>;
}
declare module 'react-spinners/cjs/RingLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/RingLoader'>;
}
declare module 'react-spinners/cjs/RiseLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/RiseLoader'>;
}
declare module 'react-spinners/cjs/RotateLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/RotateLoader'>;
}
declare module 'react-spinners/cjs/ScaleLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/ScaleLoader'>;
}
declare module 'react-spinners/cjs/SkewLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/SkewLoader'>;
}
declare module 'react-spinners/cjs/SquareLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/SquareLoader'>;
}
declare module 'react-spinners/cjs/SyncLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/SyncLoader'>;
}
declare module 'react-spinners/ClimbingBoxLoader.js' {
  declare module.exports: $Exports<'react-spinners/ClimbingBoxLoader'>;
}
declare module 'react-spinners/ClipLoader.js' {
  declare module.exports: $Exports<'react-spinners/ClipLoader'>;
}
declare module 'react-spinners/ClockLoader.js' {
  declare module.exports: $Exports<'react-spinners/ClockLoader'>;
}
declare module 'react-spinners/DotLoader.js' {
  declare module.exports: $Exports<'react-spinners/DotLoader'>;
}
declare module 'react-spinners/esm/BarLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/BarLoader'>;
}
declare module 'react-spinners/esm/BeatLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/BeatLoader'>;
}
declare module 'react-spinners/esm/BounceLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/BounceLoader'>;
}
declare module 'react-spinners/esm/CircleLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/CircleLoader'>;
}
declare module 'react-spinners/esm/ClimbingBoxLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/ClimbingBoxLoader'>;
}
declare module 'react-spinners/esm/ClipLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/ClipLoader'>;
}
declare module 'react-spinners/esm/ClockLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/ClockLoader'>;
}
declare module 'react-spinners/esm/DotLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/DotLoader'>;
}
declare module 'react-spinners/esm/FadeLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/FadeLoader'>;
}
declare module 'react-spinners/esm/GridLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/GridLoader'>;
}
declare module 'react-spinners/esm/HashLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/HashLoader'>;
}
declare module 'react-spinners/esm/helpers/animation.js' {
  declare module.exports: $Exports<'react-spinners/esm/helpers/animation'>;
}
declare module 'react-spinners/esm/helpers/animation.server.test.js' {
  declare module.exports: $Exports<'react-spinners/esm/helpers/animation.server.test'>;
}
declare module 'react-spinners/esm/helpers/animation.test.js' {
  declare module.exports: $Exports<'react-spinners/esm/helpers/animation.test'>;
}
declare module 'react-spinners/esm/helpers/colors.js' {
  declare module.exports: $Exports<'react-spinners/esm/helpers/colors'>;
}
declare module 'react-spinners/esm/helpers/colors.test.js' {
  declare module.exports: $Exports<'react-spinners/esm/helpers/colors.test'>;
}
declare module 'react-spinners/esm/helpers/props.js' {
  declare module.exports: $Exports<'react-spinners/esm/helpers/props'>;
}
declare module 'react-spinners/esm/helpers/unitConverter.js' {
  declare module.exports: $Exports<'react-spinners/esm/helpers/unitConverter'>;
}
declare module 'react-spinners/esm/helpers/unitConverter.test.js' {
  declare module.exports: $Exports<'react-spinners/esm/helpers/unitConverter.test'>;
}
declare module 'react-spinners/esm/index' {
  declare module.exports: $Exports<'react-spinners/esm'>;
}
declare module 'react-spinners/esm/index.js' {
  declare module.exports: $Exports<'react-spinners/esm'>;
}
declare module 'react-spinners/esm/MoonLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/MoonLoader'>;
}
declare module 'react-spinners/esm/PacmanLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/PacmanLoader'>;
}
declare module 'react-spinners/esm/PropagateLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/PropagateLoader'>;
}
declare module 'react-spinners/esm/PuffLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/PuffLoader'>;
}
declare module 'react-spinners/esm/PulseLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/PulseLoader'>;
}
declare module 'react-spinners/esm/RingLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/RingLoader'>;
}
declare module 'react-spinners/esm/RiseLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/RiseLoader'>;
}
declare module 'react-spinners/esm/RotateLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/RotateLoader'>;
}
declare module 'react-spinners/esm/ScaleLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/ScaleLoader'>;
}
declare module 'react-spinners/esm/SkewLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/SkewLoader'>;
}
declare module 'react-spinners/esm/SquareLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/SquareLoader'>;
}
declare module 'react-spinners/esm/SyncLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/SyncLoader'>;
}
declare module 'react-spinners/FadeLoader.js' {
  declare module.exports: $Exports<'react-spinners/FadeLoader'>;
}
declare module 'react-spinners/GridLoader.js' {
  declare module.exports: $Exports<'react-spinners/GridLoader'>;
}
declare module 'react-spinners/HashLoader.js' {
  declare module.exports: $Exports<'react-spinners/HashLoader'>;
}
declare module 'react-spinners/helpers/animation.js' {
  declare module.exports: $Exports<'react-spinners/helpers/animation'>;
}
declare module 'react-spinners/helpers/animation.server.test.js' {
  declare module.exports: $Exports<'react-spinners/helpers/animation.server.test'>;
}
declare module 'react-spinners/helpers/animation.test.js' {
  declare module.exports: $Exports<'react-spinners/helpers/animation.test'>;
}
declare module 'react-spinners/helpers/colors.js' {
  declare module.exports: $Exports<'react-spinners/helpers/colors'>;
}
declare module 'react-spinners/helpers/colors.test.js' {
  declare module.exports: $Exports<'react-spinners/helpers/colors.test'>;
}
declare module 'react-spinners/helpers/props.js' {
  declare module.exports: $Exports<'react-spinners/helpers/props'>;
}
declare module 'react-spinners/helpers/unitConverter.js' {
  declare module.exports: $Exports<'react-spinners/helpers/unitConverter'>;
}
declare module 'react-spinners/helpers/unitConverter.test.js' {
  declare module.exports: $Exports<'react-spinners/helpers/unitConverter.test'>;
}
declare module 'react-spinners/index' {
  declare module.exports: $Exports<'react-spinners'>;
}
declare module 'react-spinners/index.js' {
  declare module.exports: $Exports<'react-spinners'>;
}
declare module 'react-spinners/MoonLoader.js' {
  declare module.exports: $Exports<'react-spinners/MoonLoader'>;
}
declare module 'react-spinners/PacmanLoader.js' {
  declare module.exports: $Exports<'react-spinners/PacmanLoader'>;
}
declare module 'react-spinners/PropagateLoader.js' {
  declare module.exports: $Exports<'react-spinners/PropagateLoader'>;
}
declare module 'react-spinners/PuffLoader.js' {
  declare module.exports: $Exports<'react-spinners/PuffLoader'>;
}
declare module 'react-spinners/PulseLoader.js' {
  declare module.exports: $Exports<'react-spinners/PulseLoader'>;
}
declare module 'react-spinners/RingLoader.js' {
  declare module.exports: $Exports<'react-spinners/RingLoader'>;
}
declare module 'react-spinners/RiseLoader.js' {
  declare module.exports: $Exports<'react-spinners/RiseLoader'>;
}
declare module 'react-spinners/RotateLoader.js' {
  declare module.exports: $Exports<'react-spinners/RotateLoader'>;
}
declare module 'react-spinners/ScaleLoader.js' {
  declare module.exports: $Exports<'react-spinners/ScaleLoader'>;
}
declare module 'react-spinners/SkewLoader.js' {
  declare module.exports: $Exports<'react-spinners/SkewLoader'>;
}
declare module 'react-spinners/SquareLoader.js' {
  declare module.exports: $Exports<'react-spinners/SquareLoader'>;
}
declare module 'react-spinners/SyncLoader.js' {
  declare module.exports: $Exports<'react-spinners/SyncLoader'>;
}
declare module 'react-spinners/umd/BarLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/BarLoader'>;
}
declare module 'react-spinners/umd/BeatLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/BeatLoader'>;
}
declare module 'react-spinners/umd/BounceLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/BounceLoader'>;
}
declare module 'react-spinners/umd/CircleLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/CircleLoader'>;
}
declare module 'react-spinners/umd/ClimbingBoxLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/ClimbingBoxLoader'>;
}
declare module 'react-spinners/umd/ClipLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/ClipLoader'>;
}
declare module 'react-spinners/umd/ClockLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/ClockLoader'>;
}
declare module 'react-spinners/umd/DotLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/DotLoader'>;
}
declare module 'react-spinners/umd/FadeLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/FadeLoader'>;
}
declare module 'react-spinners/umd/GridLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/GridLoader'>;
}
declare module 'react-spinners/umd/HashLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/HashLoader'>;
}
declare module 'react-spinners/umd/helpers/animation.js' {
  declare module.exports: $Exports<'react-spinners/umd/helpers/animation'>;
}
declare module 'react-spinners/umd/helpers/animation.server.test.js' {
  declare module.exports: $Exports<'react-spinners/umd/helpers/animation.server.test'>;
}
declare module 'react-spinners/umd/helpers/animation.test.js' {
  declare module.exports: $Exports<'react-spinners/umd/helpers/animation.test'>;
}
declare module 'react-spinners/umd/helpers/colors.js' {
  declare module.exports: $Exports<'react-spinners/umd/helpers/colors'>;
}
declare module 'react-spinners/umd/helpers/colors.test.js' {
  declare module.exports: $Exports<'react-spinners/umd/helpers/colors.test'>;
}
declare module 'react-spinners/umd/helpers/props.js' {
  declare module.exports: $Exports<'react-spinners/umd/helpers/props'>;
}
declare module 'react-spinners/umd/helpers/unitConverter.js' {
  declare module.exports: $Exports<'react-spinners/umd/helpers/unitConverter'>;
}
declare module 'react-spinners/umd/helpers/unitConverter.test.js' {
  declare module.exports: $Exports<'react-spinners/umd/helpers/unitConverter.test'>;
}
declare module 'react-spinners/umd/index' {
  declare module.exports: $Exports<'react-spinners/umd'>;
}
declare module 'react-spinners/umd/index.js' {
  declare module.exports: $Exports<'react-spinners/umd'>;
}
declare module 'react-spinners/umd/MoonLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/MoonLoader'>;
}
declare module 'react-spinners/umd/PacmanLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/PacmanLoader'>;
}
declare module 'react-spinners/umd/PropagateLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/PropagateLoader'>;
}
declare module 'react-spinners/umd/PuffLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/PuffLoader'>;
}
declare module 'react-spinners/umd/PulseLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/PulseLoader'>;
}
declare module 'react-spinners/umd/RingLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/RingLoader'>;
}
declare module 'react-spinners/umd/RiseLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/RiseLoader'>;
}
declare module 'react-spinners/umd/RotateLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/RotateLoader'>;
}
declare module 'react-spinners/umd/ScaleLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/ScaleLoader'>;
}
declare module 'react-spinners/umd/SkewLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/SkewLoader'>;
}
declare module 'react-spinners/umd/SquareLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/SquareLoader'>;
}
declare module 'react-spinners/umd/SyncLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/SyncLoader'>;
}
