// flow-typed signature: 2aebf4501956624d7dcb72b0de7390bb
// flow-typed version: <<STUB>>/react-table-hoc-fixed-columns_v^2.0.1/flow_v0.199.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-table-hoc-fixed-columns'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-table-hoc-fixed-columns' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-table-hoc-fixed-columns/lib/helpers' {
  declare module.exports: any;
}

declare module 'react-table-hoc-fixed-columns/lib' {
  declare module.exports: any;
}

declare module 'react-table-hoc-fixed-columns/lib/scrollEvent' {
  declare module.exports: any;
}

declare module 'react-table-hoc-fixed-columns/lib/stickyPosition' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-table-hoc-fixed-columns/lib/helpers.js' {
  declare module.exports: $Exports<'react-table-hoc-fixed-columns/lib/helpers'>;
}
declare module 'react-table-hoc-fixed-columns/lib/index' {
  declare module.exports: $Exports<'react-table-hoc-fixed-columns/lib'>;
}
declare module 'react-table-hoc-fixed-columns/lib/index.js' {
  declare module.exports: $Exports<'react-table-hoc-fixed-columns/lib'>;
}
declare module 'react-table-hoc-fixed-columns/lib/scrollEvent/index' {
  declare module.exports: $Exports<'react-table-hoc-fixed-columns/lib/scrollEvent'>;
}
declare module 'react-table-hoc-fixed-columns/lib/scrollEvent/index.js' {
  declare module.exports: $Exports<'react-table-hoc-fixed-columns/lib/scrollEvent'>;
}
declare module 'react-table-hoc-fixed-columns/lib/stickyPosition/index' {
  declare module.exports: $Exports<'react-table-hoc-fixed-columns/lib/stickyPosition'>;
}
declare module 'react-table-hoc-fixed-columns/lib/stickyPosition/index.js' {
  declare module.exports: $Exports<'react-table-hoc-fixed-columns/lib/stickyPosition'>;
}
