// flow-typed signature: 41e2d2bc96b2781e52e05d402a9dfec4
// flow-typed version: <<STUB>>/react-beautiful-dnd_v10.0.4/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-beautiful-dnd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-beautiful-dnd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-beautiful-dnd/dist/react-beautiful-dnd.cjs' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/dist/react-beautiful-dnd.esm' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/dist/react-beautiful-dnd' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/dist/react-beautiful-dnd.min' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/debug/middleware/action-timing-average' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/debug/middleware/action-timing' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/debug/middleware/log' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/debug/middleware/user-timing' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/debug/timings' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/dev-warning' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/native-with-fallback' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/action-creators' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/auto-scroller/auto-scroller-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/auto-scroller/can-scroll' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/config' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/did-start-in-scrollable-area' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-best-scrollable-droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-droppable-scroll-change' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-percentage' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-scroll/adjust-for-size-limits' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-scroll/get-scroll-on-axis/dampen-value-by-time' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-scroll/get-scroll-on-axis/get-distance-thresholds' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-scroll/get-scroll-on-axis/get-value-from-distance' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-scroll/get-scroll-on-axis/get-value' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-scroll/get-scroll-on-axis/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-scroll/get-scroll-on-axis/min-scroll' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-scroll/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-window-scroll-change' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/scroll' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/auto-scroller/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/auto-scroller/jump-scroller' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/axis' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/can-start-drag' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/create-store' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/dimension-marshal/dimension-marshal-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/dimension-marshal/dimension-marshal' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/dimension-marshal/get-initial-publish' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/dimension-marshal/while-dragging-publisher' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/dimension-structures' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/droppable/get-droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/droppable/is-home-of' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/droppable/scroll-droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/droppable/should-use-placeholder' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/droppable/util/clip' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/droppable/util/get-subject' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/droppable/what-is-dragged-over' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/droppable/with-placeholder' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-center-from-impact/get-client-border-box-center/get-client-from-page-border-box-center' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-center-from-impact/get-client-border-box-center/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-center-from-impact/get-page-border-box-center/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-center-from-impact/get-page-border-box-center/when-combining' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-center-from-impact/get-page-border-box-center/when-reordering' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-center-from-impact/move-relative-to' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-dimension-map-with-placeholder' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-displaced-by' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-displacement-map' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-displacement' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-drag-impact/get-combine-impact' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-drag-impact/in-foreign-list' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-drag-impact/in-home-list' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-drag-impact/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-draggables-inside-droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-droppable-over' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-frame' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-home-impact' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-home-location' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-max-scroll' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/is-movement-allowed' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/is-within' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/auto-scroll' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/dimension-marshal-stopper' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/drop-animation-finish' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/drop/drop-middleware' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/drop/get-drop-duration' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/drop/get-new-home-client-offset' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/drop/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/lift' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/pending-drop' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/responders/async-marshal' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/responders/expiring-announce' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/responders/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/responders/is-equal' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/responders/publisher' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/responders/responders-middleware' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/style' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/update-viewport-max-scroll-on-destination-change' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/util/screen-reader-message-preset' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/get-best-cross-axis-droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/get-closest-draggable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/move-to-new-droppable/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/move-to-new-droppable/to-foreign-list' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/move-to-new-droppable/to-home-list' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-in-direction-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-place/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-place/is-totally-visible-in-new-location' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-place/move-to-next-combine/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-place/move-to-next-index/from-combine' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-place/move-to-next-index/from-reorder' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-place/move-to-next-index/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-place/move-to-next-index/move-to-next-index-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-place/update-displacement' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/no-impact' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/patch-droppable-map' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/position' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/post-reducer/when-moving/refresh-snap' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/post-reducer/when-moving/update' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/publish-while-dragging/adjust-additions-for-scroll-changes' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/publish-while-dragging/adjust-modified-droppables' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/publish-while-dragging/get-drag-positions' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/publish-while-dragging/get-draggable-map' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/publish-while-dragging/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/publish-while-dragging/with-no-animated-displacement' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/reducer' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/scroll-viewport' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/spacing' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/store-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/update-displacement-visibility/recompute' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/update-displacement-visibility/speculatively-increase' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/update-displacement-visibility/with-new-displacement' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/user-direction/get-user-direction' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/user-direction/is-user-moving-forward' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/user-direction/user-direction-preset' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/visibility/is-partially-visible-through-frame' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/visibility/is-position-in-frame' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/visibility/is-totally-visible-through-frame-on-axis' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/visibility/is-totally-visible-through-frame' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/visibility/is-visible' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/will-displace-forward' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/with-scroll-change/with-all-displacement' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/with-scroll-change/with-droppable-displacement' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/with-scroll-change/with-droppable-scroll' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/with-scroll-change/with-viewport-displacement' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/animation' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/announcer/announcer-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/announcer/announcer' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/context-keys' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/data-attributes' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-drop-context/check-doctype' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-drop-context/check-react-version' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-drop-context/drag-drop-context' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-drop-context/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/drag-handle-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/drag-handle' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/sensor/create-keyboard-sensor' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/sensor/create-mouse-sensor' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/sensor/create-touch-sensor' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/sensor/sensor-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/util/bind-events' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/util/create-event-marshal' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/util/create-post-drag-event-preventer' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/util/create-scheduler' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/util/event-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/util/focus-retainer' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/util/get-drag-handle-ref' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/util/is-sloppy-click-threshold-exceeded' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/util/prevent-standard-key-events' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/util/should-allow-dragging-from-target' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/util/supported-page-visibility-event-name' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable-dimension-publisher/draggable-dimension-publisher' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable-dimension-publisher/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable/check-own-props' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable/connected-draggable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable/draggable-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable/draggable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/check-for-nested-scroll-container' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/droppable-dimension-publisher' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/get-closest-scrollable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/get-dimension' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/get-env' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/get-scroll' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/is-in-fixed-container' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable/check-own-props' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable/connected-droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable/droppable-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable/droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/get-body-element' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/get-border-box-center-position' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/get-document-element' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/is-strict-equal' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/is-type-of-element/is-element' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/is-type-of-element/is-html-element' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/is-type-of-element/is-svg-element' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/key-codes' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/placeholder/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/placeholder/placeholder-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/placeholder/placeholder' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/style-marshal/get-styles' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/style-marshal/style-marshal-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/style-marshal/style-marshal' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/throw-if-invalid-inner-ref' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/window/get-max-window-scroll' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/window/get-viewport' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/window/get-window-from-el' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/window/get-window-scroll' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/window/scroll-window' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-beautiful-dnd/dist/react-beautiful-dnd.cjs.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/dist/react-beautiful-dnd.cjs'>;
}
declare module 'react-beautiful-dnd/dist/react-beautiful-dnd.esm.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/dist/react-beautiful-dnd.esm'>;
}
declare module 'react-beautiful-dnd/dist/react-beautiful-dnd.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/dist/react-beautiful-dnd'>;
}
declare module 'react-beautiful-dnd/dist/react-beautiful-dnd.min.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/dist/react-beautiful-dnd.min'>;
}
declare module 'react-beautiful-dnd/src/debug/middleware/action-timing-average.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/debug/middleware/action-timing-average'>;
}
declare module 'react-beautiful-dnd/src/debug/middleware/action-timing.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/debug/middleware/action-timing'>;
}
declare module 'react-beautiful-dnd/src/debug/middleware/log.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/debug/middleware/log'>;
}
declare module 'react-beautiful-dnd/src/debug/middleware/user-timing.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/debug/middleware/user-timing'>;
}
declare module 'react-beautiful-dnd/src/debug/timings.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/debug/timings'>;
}
declare module 'react-beautiful-dnd/src/dev-warning.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/dev-warning'>;
}
declare module 'react-beautiful-dnd/src/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/index'>;
}
declare module 'react-beautiful-dnd/src/native-with-fallback.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/native-with-fallback'>;
}
declare module 'react-beautiful-dnd/src/state/action-creators.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/action-creators'>;
}
declare module 'react-beautiful-dnd/src/state/auto-scroller/auto-scroller-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/auto-scroller/auto-scroller-types'>;
}
declare module 'react-beautiful-dnd/src/state/auto-scroller/can-scroll.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/auto-scroller/can-scroll'>;
}
declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/config.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/config'>;
}
declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/did-start-in-scrollable-area.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/did-start-in-scrollable-area'>;
}
declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-best-scrollable-droppable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-best-scrollable-droppable'>;
}
declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-droppable-scroll-change.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-droppable-scroll-change'>;
}
declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-percentage.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-percentage'>;
}
declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-scroll/adjust-for-size-limits.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-scroll/adjust-for-size-limits'>;
}
declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-scroll/get-scroll-on-axis/dampen-value-by-time.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-scroll/get-scroll-on-axis/dampen-value-by-time'>;
}
declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-scroll/get-scroll-on-axis/get-distance-thresholds.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-scroll/get-scroll-on-axis/get-distance-thresholds'>;
}
declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-scroll/get-scroll-on-axis/get-value-from-distance.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-scroll/get-scroll-on-axis/get-value-from-distance'>;
}
declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-scroll/get-scroll-on-axis/get-value.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-scroll/get-scroll-on-axis/get-value'>;
}
declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-scroll/get-scroll-on-axis/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-scroll/get-scroll-on-axis/index'>;
}
declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-scroll/get-scroll-on-axis/min-scroll.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-scroll/get-scroll-on-axis/min-scroll'>;
}
declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-scroll/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-scroll/index'>;
}
declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-window-scroll-change.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/get-window-scroll-change'>;
}
declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/index'>;
}
declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/scroll.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller/scroll'>;
}
declare module 'react-beautiful-dnd/src/state/auto-scroller/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/auto-scroller/index'>;
}
declare module 'react-beautiful-dnd/src/state/auto-scroller/jump-scroller.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/auto-scroller/jump-scroller'>;
}
declare module 'react-beautiful-dnd/src/state/axis.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/axis'>;
}
declare module 'react-beautiful-dnd/src/state/can-start-drag.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/can-start-drag'>;
}
declare module 'react-beautiful-dnd/src/state/create-store.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/create-store'>;
}
declare module 'react-beautiful-dnd/src/state/dimension-marshal/dimension-marshal-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/dimension-marshal/dimension-marshal-types'>;
}
declare module 'react-beautiful-dnd/src/state/dimension-marshal/dimension-marshal.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/dimension-marshal/dimension-marshal'>;
}
declare module 'react-beautiful-dnd/src/state/dimension-marshal/get-initial-publish.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/dimension-marshal/get-initial-publish'>;
}
declare module 'react-beautiful-dnd/src/state/dimension-marshal/while-dragging-publisher.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/dimension-marshal/while-dragging-publisher'>;
}
declare module 'react-beautiful-dnd/src/state/dimension-structures.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/dimension-structures'>;
}
declare module 'react-beautiful-dnd/src/state/droppable/get-droppable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/droppable/get-droppable'>;
}
declare module 'react-beautiful-dnd/src/state/droppable/is-home-of.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/droppable/is-home-of'>;
}
declare module 'react-beautiful-dnd/src/state/droppable/scroll-droppable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/droppable/scroll-droppable'>;
}
declare module 'react-beautiful-dnd/src/state/droppable/should-use-placeholder.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/droppable/should-use-placeholder'>;
}
declare module 'react-beautiful-dnd/src/state/droppable/util/clip.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/droppable/util/clip'>;
}
declare module 'react-beautiful-dnd/src/state/droppable/util/get-subject.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/droppable/util/get-subject'>;
}
declare module 'react-beautiful-dnd/src/state/droppable/what-is-dragged-over.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/droppable/what-is-dragged-over'>;
}
declare module 'react-beautiful-dnd/src/state/droppable/with-placeholder.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/droppable/with-placeholder'>;
}
declare module 'react-beautiful-dnd/src/state/get-center-from-impact/get-client-border-box-center/get-client-from-page-border-box-center.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-center-from-impact/get-client-border-box-center/get-client-from-page-border-box-center'>;
}
declare module 'react-beautiful-dnd/src/state/get-center-from-impact/get-client-border-box-center/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-center-from-impact/get-client-border-box-center/index'>;
}
declare module 'react-beautiful-dnd/src/state/get-center-from-impact/get-page-border-box-center/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-center-from-impact/get-page-border-box-center/index'>;
}
declare module 'react-beautiful-dnd/src/state/get-center-from-impact/get-page-border-box-center/when-combining.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-center-from-impact/get-page-border-box-center/when-combining'>;
}
declare module 'react-beautiful-dnd/src/state/get-center-from-impact/get-page-border-box-center/when-reordering.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-center-from-impact/get-page-border-box-center/when-reordering'>;
}
declare module 'react-beautiful-dnd/src/state/get-center-from-impact/move-relative-to.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-center-from-impact/move-relative-to'>;
}
declare module 'react-beautiful-dnd/src/state/get-dimension-map-with-placeholder.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-dimension-map-with-placeholder'>;
}
declare module 'react-beautiful-dnd/src/state/get-displaced-by.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-displaced-by'>;
}
declare module 'react-beautiful-dnd/src/state/get-displacement-map.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-displacement-map'>;
}
declare module 'react-beautiful-dnd/src/state/get-displacement.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-displacement'>;
}
declare module 'react-beautiful-dnd/src/state/get-drag-impact/get-combine-impact.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-drag-impact/get-combine-impact'>;
}
declare module 'react-beautiful-dnd/src/state/get-drag-impact/in-foreign-list.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-drag-impact/in-foreign-list'>;
}
declare module 'react-beautiful-dnd/src/state/get-drag-impact/in-home-list.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-drag-impact/in-home-list'>;
}
declare module 'react-beautiful-dnd/src/state/get-drag-impact/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-drag-impact/index'>;
}
declare module 'react-beautiful-dnd/src/state/get-draggables-inside-droppable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-draggables-inside-droppable'>;
}
declare module 'react-beautiful-dnd/src/state/get-droppable-over.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-droppable-over'>;
}
declare module 'react-beautiful-dnd/src/state/get-frame.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-frame'>;
}
declare module 'react-beautiful-dnd/src/state/get-home-impact.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-home-impact'>;
}
declare module 'react-beautiful-dnd/src/state/get-home-location.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-home-location'>;
}
declare module 'react-beautiful-dnd/src/state/get-max-scroll.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-max-scroll'>;
}
declare module 'react-beautiful-dnd/src/state/is-movement-allowed.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/is-movement-allowed'>;
}
declare module 'react-beautiful-dnd/src/state/is-within.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/is-within'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/auto-scroll.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/auto-scroll'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/dimension-marshal-stopper.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/dimension-marshal-stopper'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/drop-animation-finish.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/drop-animation-finish'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/drop/drop-middleware.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/drop/drop-middleware'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/drop/get-drop-duration.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/drop/get-drop-duration'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/drop/get-new-home-client-offset.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/drop/get-new-home-client-offset'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/drop/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/drop/index'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/lift.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/lift'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/pending-drop.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/pending-drop'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/responders/async-marshal.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/responders/async-marshal'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/responders/expiring-announce.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/responders/expiring-announce'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/responders/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/responders/index'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/responders/is-equal.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/responders/is-equal'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/responders/publisher.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/responders/publisher'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/responders/responders-middleware.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/responders/responders-middleware'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/style.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/style'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/update-viewport-max-scroll-on-destination-change.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/update-viewport-max-scroll-on-destination-change'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/util/screen-reader-message-preset.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/util/screen-reader-message-preset'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/index'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/get-best-cross-axis-droppable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/get-best-cross-axis-droppable'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/get-closest-draggable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/get-closest-draggable'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/index'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/move-to-new-droppable/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/move-to-new-droppable/index'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/move-to-new-droppable/to-foreign-list.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/move-to-new-droppable/to-foreign-list'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/move-to-new-droppable/to-home-list.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/move-to-new-droppable/to-home-list'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-in-direction-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-in-direction-types'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-place/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-to-next-place/index'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-place/is-totally-visible-in-new-location.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-to-next-place/is-totally-visible-in-new-location'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-place/move-to-next-combine/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-to-next-place/move-to-next-combine/index'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-place/move-to-next-index/from-combine.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-to-next-place/move-to-next-index/from-combine'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-place/move-to-next-index/from-reorder.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-to-next-place/move-to-next-index/from-reorder'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-place/move-to-next-index/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-to-next-place/move-to-next-index/index'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-place/move-to-next-index/move-to-next-index-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-to-next-place/move-to-next-index/move-to-next-index-types'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-place/update-displacement.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-to-next-place/update-displacement'>;
}
declare module 'react-beautiful-dnd/src/state/no-impact.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/no-impact'>;
}
declare module 'react-beautiful-dnd/src/state/patch-droppable-map.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/patch-droppable-map'>;
}
declare module 'react-beautiful-dnd/src/state/position.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/position'>;
}
declare module 'react-beautiful-dnd/src/state/post-reducer/when-moving/refresh-snap.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/post-reducer/when-moving/refresh-snap'>;
}
declare module 'react-beautiful-dnd/src/state/post-reducer/when-moving/update.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/post-reducer/when-moving/update'>;
}
declare module 'react-beautiful-dnd/src/state/publish-while-dragging/adjust-additions-for-scroll-changes.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/publish-while-dragging/adjust-additions-for-scroll-changes'>;
}
declare module 'react-beautiful-dnd/src/state/publish-while-dragging/adjust-modified-droppables.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/publish-while-dragging/adjust-modified-droppables'>;
}
declare module 'react-beautiful-dnd/src/state/publish-while-dragging/get-drag-positions.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/publish-while-dragging/get-drag-positions'>;
}
declare module 'react-beautiful-dnd/src/state/publish-while-dragging/get-draggable-map.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/publish-while-dragging/get-draggable-map'>;
}
declare module 'react-beautiful-dnd/src/state/publish-while-dragging/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/publish-while-dragging/index'>;
}
declare module 'react-beautiful-dnd/src/state/publish-while-dragging/with-no-animated-displacement.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/publish-while-dragging/with-no-animated-displacement'>;
}
declare module 'react-beautiful-dnd/src/state/reducer.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/reducer'>;
}
declare module 'react-beautiful-dnd/src/state/scroll-viewport.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/scroll-viewport'>;
}
declare module 'react-beautiful-dnd/src/state/spacing.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/spacing'>;
}
declare module 'react-beautiful-dnd/src/state/store-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/store-types'>;
}
declare module 'react-beautiful-dnd/src/state/update-displacement-visibility/recompute.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/update-displacement-visibility/recompute'>;
}
declare module 'react-beautiful-dnd/src/state/update-displacement-visibility/speculatively-increase.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/update-displacement-visibility/speculatively-increase'>;
}
declare module 'react-beautiful-dnd/src/state/update-displacement-visibility/with-new-displacement.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/update-displacement-visibility/with-new-displacement'>;
}
declare module 'react-beautiful-dnd/src/state/user-direction/get-user-direction.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/user-direction/get-user-direction'>;
}
declare module 'react-beautiful-dnd/src/state/user-direction/is-user-moving-forward.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/user-direction/is-user-moving-forward'>;
}
declare module 'react-beautiful-dnd/src/state/user-direction/user-direction-preset.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/user-direction/user-direction-preset'>;
}
declare module 'react-beautiful-dnd/src/state/visibility/is-partially-visible-through-frame.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/visibility/is-partially-visible-through-frame'>;
}
declare module 'react-beautiful-dnd/src/state/visibility/is-position-in-frame.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/visibility/is-position-in-frame'>;
}
declare module 'react-beautiful-dnd/src/state/visibility/is-totally-visible-through-frame-on-axis.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/visibility/is-totally-visible-through-frame-on-axis'>;
}
declare module 'react-beautiful-dnd/src/state/visibility/is-totally-visible-through-frame.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/visibility/is-totally-visible-through-frame'>;
}
declare module 'react-beautiful-dnd/src/state/visibility/is-visible.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/visibility/is-visible'>;
}
declare module 'react-beautiful-dnd/src/state/will-displace-forward.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/will-displace-forward'>;
}
declare module 'react-beautiful-dnd/src/state/with-scroll-change/with-all-displacement.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/with-scroll-change/with-all-displacement'>;
}
declare module 'react-beautiful-dnd/src/state/with-scroll-change/with-droppable-displacement.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/with-scroll-change/with-droppable-displacement'>;
}
declare module 'react-beautiful-dnd/src/state/with-scroll-change/with-droppable-scroll.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/with-scroll-change/with-droppable-scroll'>;
}
declare module 'react-beautiful-dnd/src/state/with-scroll-change/with-viewport-displacement.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/with-scroll-change/with-viewport-displacement'>;
}
declare module 'react-beautiful-dnd/src/types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/types'>;
}
declare module 'react-beautiful-dnd/src/view/animation.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/animation'>;
}
declare module 'react-beautiful-dnd/src/view/announcer/announcer-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/announcer/announcer-types'>;
}
declare module 'react-beautiful-dnd/src/view/announcer/announcer.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/announcer/announcer'>;
}
declare module 'react-beautiful-dnd/src/view/context-keys.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/context-keys'>;
}
declare module 'react-beautiful-dnd/src/view/data-attributes.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/data-attributes'>;
}
declare module 'react-beautiful-dnd/src/view/drag-drop-context/check-doctype.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-drop-context/check-doctype'>;
}
declare module 'react-beautiful-dnd/src/view/drag-drop-context/check-react-version.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-drop-context/check-react-version'>;
}
declare module 'react-beautiful-dnd/src/view/drag-drop-context/drag-drop-context.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-drop-context/drag-drop-context'>;
}
declare module 'react-beautiful-dnd/src/view/drag-drop-context/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-drop-context/index'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/drag-handle-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/drag-handle-types'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/drag-handle.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/drag-handle'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/index'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/sensor/create-keyboard-sensor.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/sensor/create-keyboard-sensor'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/sensor/create-mouse-sensor.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/sensor/create-mouse-sensor'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/sensor/create-touch-sensor.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/sensor/create-touch-sensor'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/sensor/sensor-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/sensor/sensor-types'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/util/bind-events.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/util/bind-events'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/util/create-event-marshal.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/util/create-event-marshal'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/util/create-post-drag-event-preventer.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/util/create-post-drag-event-preventer'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/util/create-scheduler.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/util/create-scheduler'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/util/event-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/util/event-types'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/util/focus-retainer.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/util/focus-retainer'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/util/get-drag-handle-ref.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/util/get-drag-handle-ref'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/util/is-sloppy-click-threshold-exceeded.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/util/is-sloppy-click-threshold-exceeded'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/util/prevent-standard-key-events.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/util/prevent-standard-key-events'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/util/should-allow-dragging-from-target.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/util/should-allow-dragging-from-target'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/util/supported-page-visibility-event-name.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/util/supported-page-visibility-event-name'>;
}
declare module 'react-beautiful-dnd/src/view/draggable-dimension-publisher/draggable-dimension-publisher.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable-dimension-publisher/draggable-dimension-publisher'>;
}
declare module 'react-beautiful-dnd/src/view/draggable-dimension-publisher/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable-dimension-publisher/index'>;
}
declare module 'react-beautiful-dnd/src/view/draggable/check-own-props.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable/check-own-props'>;
}
declare module 'react-beautiful-dnd/src/view/draggable/connected-draggable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable/connected-draggable'>;
}
declare module 'react-beautiful-dnd/src/view/draggable/draggable-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable/draggable-types'>;
}
declare module 'react-beautiful-dnd/src/view/draggable/draggable.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable/draggable'>;
}
declare module 'react-beautiful-dnd/src/view/draggable/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable/index'>;
}
declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/check-for-nested-scroll-container.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable-dimension-publisher/check-for-nested-scroll-container'>;
}
declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/droppable-dimension-publisher.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable-dimension-publisher/droppable-dimension-publisher'>;
}
declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/get-closest-scrollable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable-dimension-publisher/get-closest-scrollable'>;
}
declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/get-dimension.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable-dimension-publisher/get-dimension'>;
}
declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/get-env.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable-dimension-publisher/get-env'>;
}
declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/get-scroll.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable-dimension-publisher/get-scroll'>;
}
declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable-dimension-publisher/index'>;
}
declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/is-in-fixed-container.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable-dimension-publisher/is-in-fixed-container'>;
}
declare module 'react-beautiful-dnd/src/view/droppable/check-own-props.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable/check-own-props'>;
}
declare module 'react-beautiful-dnd/src/view/droppable/connected-droppable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable/connected-droppable'>;
}
declare module 'react-beautiful-dnd/src/view/droppable/droppable-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable/droppable-types'>;
}
declare module 'react-beautiful-dnd/src/view/droppable/droppable.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable/droppable'>;
}
declare module 'react-beautiful-dnd/src/view/droppable/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable/index'>;
}
declare module 'react-beautiful-dnd/src/view/get-body-element.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/get-body-element'>;
}
declare module 'react-beautiful-dnd/src/view/get-border-box-center-position.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/get-border-box-center-position'>;
}
declare module 'react-beautiful-dnd/src/view/get-document-element.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/get-document-element'>;
}
declare module 'react-beautiful-dnd/src/view/is-strict-equal.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/is-strict-equal'>;
}
declare module 'react-beautiful-dnd/src/view/is-type-of-element/is-element.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/is-type-of-element/is-element'>;
}
declare module 'react-beautiful-dnd/src/view/is-type-of-element/is-html-element.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/is-type-of-element/is-html-element'>;
}
declare module 'react-beautiful-dnd/src/view/is-type-of-element/is-svg-element.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/is-type-of-element/is-svg-element'>;
}
declare module 'react-beautiful-dnd/src/view/key-codes.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/key-codes'>;
}
declare module 'react-beautiful-dnd/src/view/placeholder/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/placeholder/index'>;
}
declare module 'react-beautiful-dnd/src/view/placeholder/placeholder-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/placeholder/placeholder-types'>;
}
declare module 'react-beautiful-dnd/src/view/placeholder/placeholder.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/placeholder/placeholder'>;
}
declare module 'react-beautiful-dnd/src/view/style-marshal/get-styles.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/style-marshal/get-styles'>;
}
declare module 'react-beautiful-dnd/src/view/style-marshal/style-marshal-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/style-marshal/style-marshal-types'>;
}
declare module 'react-beautiful-dnd/src/view/style-marshal/style-marshal.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/style-marshal/style-marshal'>;
}
declare module 'react-beautiful-dnd/src/view/throw-if-invalid-inner-ref.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/throw-if-invalid-inner-ref'>;
}
declare module 'react-beautiful-dnd/src/view/window/get-max-window-scroll.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/window/get-max-window-scroll'>;
}
declare module 'react-beautiful-dnd/src/view/window/get-viewport.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/window/get-viewport'>;
}
declare module 'react-beautiful-dnd/src/view/window/get-window-from-el.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/window/get-window-from-el'>;
}
declare module 'react-beautiful-dnd/src/view/window/get-window-scroll.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/window/get-window-scroll'>;
}
declare module 'react-beautiful-dnd/src/view/window/scroll-window.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/window/scroll-window'>;
}
