// flow-typed signature: 8f374f6d4d11e72b42ea6dd42824f289
// flow-typed version: <<STUB>>/shapefile_v^0.6.6/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shapefile'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shapefile' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'shapefile/dbf/boolean' {
  declare module.exports: any;
}

declare module 'shapefile/dbf/cancel' {
  declare module.exports: any;
}

declare module 'shapefile/dbf/date' {
  declare module.exports: any;
}

declare module 'shapefile/dbf/index' {
  declare module.exports: any;
}

declare module 'shapefile/dbf/number' {
  declare module.exports: any;
}

declare module 'shapefile/dbf/read' {
  declare module.exports: any;
}

declare module 'shapefile/dbf/string' {
  declare module.exports: any;
}

declare module 'shapefile/dist/shapefile' {
  declare module.exports: any;
}

declare module 'shapefile/dist/shapefile.min' {
  declare module.exports: any;
}

declare module 'shapefile/dist/shapefile.node' {
  declare module.exports: any;
}

declare module 'shapefile/index.node' {
  declare module.exports: any;
}

declare module 'shapefile/rollup.config' {
  declare module.exports: any;
}

declare module 'shapefile/shapefile/cancel' {
  declare module.exports: any;
}

declare module 'shapefile/shapefile/index' {
  declare module.exports: any;
}

declare module 'shapefile/shapefile/read' {
  declare module.exports: any;
}

declare module 'shapefile/shp/cancel' {
  declare module.exports: any;
}

declare module 'shapefile/shp/concat' {
  declare module.exports: any;
}

declare module 'shapefile/shp/index' {
  declare module.exports: any;
}

declare module 'shapefile/shp/multipoint' {
  declare module.exports: any;
}

declare module 'shapefile/shp/null' {
  declare module.exports: any;
}

declare module 'shapefile/shp/point' {
  declare module.exports: any;
}

declare module 'shapefile/shp/polygon' {
  declare module.exports: any;
}

declare module 'shapefile/shp/polyline' {
  declare module.exports: any;
}

declare module 'shapefile/shp/read' {
  declare module.exports: any;
}

declare module 'shapefile/view' {
  declare module.exports: any;
}

// Filename aliases
declare module 'shapefile/dbf/boolean.js' {
  declare module.exports: $Exports<'shapefile/dbf/boolean'>;
}
declare module 'shapefile/dbf/cancel.js' {
  declare module.exports: $Exports<'shapefile/dbf/cancel'>;
}
declare module 'shapefile/dbf/date.js' {
  declare module.exports: $Exports<'shapefile/dbf/date'>;
}
declare module 'shapefile/dbf/index.js' {
  declare module.exports: $Exports<'shapefile/dbf/index'>;
}
declare module 'shapefile/dbf/number.js' {
  declare module.exports: $Exports<'shapefile/dbf/number'>;
}
declare module 'shapefile/dbf/read.js' {
  declare module.exports: $Exports<'shapefile/dbf/read'>;
}
declare module 'shapefile/dbf/string.js' {
  declare module.exports: $Exports<'shapefile/dbf/string'>;
}
declare module 'shapefile/dist/shapefile.js' {
  declare module.exports: $Exports<'shapefile/dist/shapefile'>;
}
declare module 'shapefile/dist/shapefile.min.js' {
  declare module.exports: $Exports<'shapefile/dist/shapefile.min'>;
}
declare module 'shapefile/dist/shapefile.node.js' {
  declare module.exports: $Exports<'shapefile/dist/shapefile.node'>;
}
declare module 'shapefile/index' {
  declare module.exports: $Exports<'shapefile'>;
}
declare module 'shapefile/index.js' {
  declare module.exports: $Exports<'shapefile'>;
}
declare module 'shapefile/index.node.js' {
  declare module.exports: $Exports<'shapefile/index.node'>;
}
declare module 'shapefile/rollup.config.js' {
  declare module.exports: $Exports<'shapefile/rollup.config'>;
}
declare module 'shapefile/shapefile/cancel.js' {
  declare module.exports: $Exports<'shapefile/shapefile/cancel'>;
}
declare module 'shapefile/shapefile/index.js' {
  declare module.exports: $Exports<'shapefile/shapefile/index'>;
}
declare module 'shapefile/shapefile/read.js' {
  declare module.exports: $Exports<'shapefile/shapefile/read'>;
}
declare module 'shapefile/shp/cancel.js' {
  declare module.exports: $Exports<'shapefile/shp/cancel'>;
}
declare module 'shapefile/shp/concat.js' {
  declare module.exports: $Exports<'shapefile/shp/concat'>;
}
declare module 'shapefile/shp/index.js' {
  declare module.exports: $Exports<'shapefile/shp/index'>;
}
declare module 'shapefile/shp/multipoint.js' {
  declare module.exports: $Exports<'shapefile/shp/multipoint'>;
}
declare module 'shapefile/shp/null.js' {
  declare module.exports: $Exports<'shapefile/shp/null'>;
}
declare module 'shapefile/shp/point.js' {
  declare module.exports: $Exports<'shapefile/shp/point'>;
}
declare module 'shapefile/shp/polygon.js' {
  declare module.exports: $Exports<'shapefile/shp/polygon'>;
}
declare module 'shapefile/shp/polyline.js' {
  declare module.exports: $Exports<'shapefile/shp/polyline'>;
}
declare module 'shapefile/shp/read.js' {
  declare module.exports: $Exports<'shapefile/shp/read'>;
}
declare module 'shapefile/view.js' {
  declare module.exports: $Exports<'shapefile/view'>;
}
