// flow-typed signature: 23d7ce3328b65876b0d93025903a4a91
// flow-typed version: <<STUB>>/sw-offline-cache_vgit+https://github.com/sitowise/sw-offline-cache.git/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sw-offline-cache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sw-offline-cache' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sw-offline-cache/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sw-offline-cache/index' {
  declare module.exports: $Exports<'sw-offline-cache'>;
}
declare module 'sw-offline-cache/index.js' {
  declare module.exports: $Exports<'sw-offline-cache'>;
}
declare module 'sw-offline-cache/test.js' {
  declare module.exports: $Exports<'sw-offline-cache/test'>;
}
