// flow-typed signature: 7beddd988b4906fed1d6d4b1281a735d
// flow-typed version: <<STUB>>/use-resize-observer_v^9.1.0/flow_v0.199.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'use-resize-observer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'use-resize-observer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'use-resize-observer/dist/bundle.cjs' {
  declare module.exports: any;
}

declare module 'use-resize-observer/dist/bundle.esm' {
  declare module.exports: any;
}

declare module 'use-resize-observer/polyfilled' {
  declare module.exports: any;
}

// Filename aliases
declare module 'use-resize-observer/dist/bundle.cjs.js' {
  declare module.exports: $Exports<'use-resize-observer/dist/bundle.cjs'>;
}
declare module 'use-resize-observer/dist/bundle.esm.js' {
  declare module.exports: $Exports<'use-resize-observer/dist/bundle.esm'>;
}
declare module 'use-resize-observer/polyfilled.js' {
  declare module.exports: $Exports<'use-resize-observer/polyfilled'>;
}
