// flow-typed signature: d7d22e25aa13f48d988e1827248afc3a
// flow-typed version: <<STUB>>/util_v^0.12.5/flow_v0.199.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'util'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'util' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'util/support/isBuffer' {
  declare module.exports: any;
}

declare module 'util/support/isBufferBrowser' {
  declare module.exports: any;
}

declare module 'util/support/types' {
  declare module.exports: any;
}

declare module 'util/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'util/support/isBuffer.js' {
  declare module.exports: $Exports<'util/support/isBuffer'>;
}
declare module 'util/support/isBufferBrowser.js' {
  declare module.exports: $Exports<'util/support/isBufferBrowser'>;
}
declare module 'util/support/types.js' {
  declare module.exports: $Exports<'util/support/types'>;
}
declare module 'util/util.js' {
  declare module.exports: $Exports<'util/util'>;
}
