ALTER TABLE LAYER ADD EDITABLE_COLUMNS QUERY_COLUMN_TYPE;

UPDATE LAYER SET EDITABLE_COLUMNS = QUERY_COLUMN_TYPE('PROPERTY_ID','NOTES','OWNER_UNCLEAR') WHERE ID IN (SELECT ID FROM LAYER WHERE NAME = 'Väyläviraston kiinteistöt');
