INSERT INTO RELATION
    (LAYER_ID, RELATION_LAYER_ID, RELATION_COLUMN_IN, RELATION_COLUMN_OUT, RELATION_TYPE)
SELECT
    ID AS LAYER_ID, RELATION_LAYER_ID, RELATION_COLUMN_IN, RELATION_COLUMN_OUT, RELATION_TYPE
FROM
    LAYER
WHERE
    RELATION_TYPE IS NOT NULL;
