DELETE FROM LAYER_PERMISSION WHERE (LAYER_ID = (SELECT ID FROM LAYER WHERE NAME = 'Väyläviraston kiinteistöt')) AND USER_GROUP = 'KSR_ROLE_ADMIN';
INSERT INTO LAYER_PERMISSION (LAYER_ID, USER_GROUP, CREATE_LAYER, READ_LAYER, UPDATE_LAYER, DELETE_LAYER) VALUES ((SELECT ID FROM LAYER WHERE NAME = 'Väyläviraston kiinteistöt'), 'KSR_ROLE_ADMIN', '1', '1', '1', '1');
