// Sidenav
export const GET_ACTIVE_NAV = 'GET_ACTIVE_NAV';
export const SET_ACTIVE_NAV = 'SET_ACTIVE_NAV';

// Map
export const SET_MAP_VIEW = 'SET_MAP_VIEW';
export const SET_MAP_TOOLS = 'SET_MAP_TOOLS';
export const SET_ACTIVE_TOOL = 'SET_ACTIVE_TOOL';
export const SET_ACTIVE_TOOL_MENU = 'SET_ACTIVE_TOOL_MENU';
export const SET_EDIT_MODE = 'SET_EDIT_MODE';

export const REMOVE_LAYER_FROM_VIEW = 'REMOVE_LAYER_FROM_VIEW';
export const REMOVE_LAYERS_VIEW = 'REMOVE_LAYERS_VIEW';

// Layers
export const GET_LAYER_GROUPS = 'GET_LAYER_GROUPS';
export const GET_LAYER_GROUPS_FULFILLED = 'GET_LAYER_GROUPS_FULFILLED';

export const SET_LAYER_LIST = 'SET_LAYER_LIST';

export const GET_ACTIVE_LAYER_TAB = 'GET_ACTIVE_LAYER_TAB';
export const SET_ACTIVE_LAYER_TAB = 'SET_ACTIVE_LAYER_TAB';

export const HIDE_LAYER = 'HIDE_LAYER';
export const ADD_SEARCH_RESULTS_LAYER = 'ADD_SEARCH_RESULTS_LAYER';

export const SET_GRAPH_LAYER = 'SET_GRAPH_LAYER';

export const ADD_USER_LAYER = 'ADD_USER_LAYER';

// Map config
export const GET_MAP_CONFIG = 'GET_MAP_CONFIG';
export const GET_MAP_CONFIG_FULFILLED = 'GET_MAP_CONFIG_FULFILLED';

// Table
export const TOGGLE_TABLE = 'TOGGLE_TABLE';
export const TOGGLE_FILTER = 'TOGGLE_FILTER';

export const SELECT_FEATURES = 'SELECT_FEATURES';
export const DE_SELECT_SELECTED_FEATURES = 'DE_SELECT_SELECTED_FEATURES';
export const TOGGLE_SELECTION = 'TOGGLE_SELECTION';
export const TOGGLE_SELECT_ALL = 'TOGGLE_SELECT_ALL';

export const SET_ACTIVE_TABLE = 'SET_ACTIVE_TABLE';
export const SET_COLUMNS = 'SET_COLUMNS';

export const CLEAR_TABLE_DATA = 'CLEAR_TABLE_DATA';
export const SET_EDITED_LAYER = 'SET_EDITED_LAYER';

export const SET_SINGLE_LAYER_GEOMETRY = 'SET_SINGLE_LAYER_GEOMETRY';

export const APPLY_EDITS = 'APPLY_EDITS';

// Search
export const SEARCH_FEATURES = 'SEARCH_FEATURES';
export const SEARCH_FEATURES_FULFILLED = 'SEARCH_FEATURES_FULFILLED';

export const SET_SEARCH_STATE = 'SET_SEARCH_STATE';
export const SET_SEARCH_OPTIONS = 'SET_SEARCH_OPTIONS';

// Modal
export const SET_ACTIVE_MODAL = 'SET_ACTIVE_MODAL';
export const SET_DROPZONE_ACTIVE = 'SET_DROPZONE_ACTIVE';

// Admin tools
export const SET_ACTIVE_ADMIN_TOOL = 'SET_ACTIVE_ADMIN_TOOL';
export const DELETE_SELECTED_DATA = 'DELETE_SELECTED_DATA';

// User layer
export const REMOVE_USER_LAYER = 'REMOVE_USER_LAYER';
export const REMOVE_USER_LAYER_FULFILLED = 'REMOVE_USER_LAYER_FULFILLED';

// Workspace
export const GET_WORKSPACE_LIST = 'GET_WORKSPACE_LIST';
export const GET_WORKSPACE_LIST_FULFILLED = 'GET_WORKSPACE_LIST_FULFILLED';

// Shapefile
export const ADD_SHAPEFILE_LAYER = 'ADD_SHAPEFILE_LAYER';

// Confirm modal
export const SHOW_CONFIRM_MODAL = 'SHOW_CONFIRM_MODAL';
export const HIDE_CONFIRM_MODAL = 'HIDE_CONFIRM_MODAL';

// Map draw
export const SET_MAP_DRAW_TEXT = 'SET_MAP_DRAW_TEXT';
export const SET_HAS_GRAPHICS = 'SET_HAS_GRAPHICS';
