// Sidenav
export const GET_ACTIVE_NAV = 'GET_ACTIVE_NAV';
export const SET_ACTIVE_NAV = 'SET_ACTIVE_NAV';

// Map layers
export const GET_WMS_LAYERS = 'GET_WMS_LAYERS';
export const SET_WMS_LAYERS = 'SET_WMS_LAYERS';

export const GET_WMTS_LAYERS = 'GET_WMTS_LAYERS';
export const SET_WMTS_LAYERS = 'SET_WMTS_LAYERS';

export const GET_LAYER_GROUPS = 'GET_LAYER_GROUPS';

export const GET_ACTIVE_LAYER_TAB = 'GET_ACTIVE_LAYER_TAB';
export const SET_ACTIVE_LAYER_TAB = 'SET_ACTIVE_LAYER_TAB';

export const GET_ACTIVE_LAYERS = 'GET_ACTIVE_LAYERS';
export const SET_ACTIVE_LAYERS = 'SET_ACTIVE_LAYERS';

