// Sidenav
export const GET_ACTIVE_NAV = 'GET_ACTIVE_NAV';
export const SET_ACTIVE_NAV = 'SET_ACTIVE_NAV';

// Map layers
export const GET_LAYER_GROUPS = 'GET_LAYER_GROUPS';
export const GET_LAYER_GROUPS_FULFILLED = 'GET_LAYER_GROUPS_FULFILLED';

export const SET_LAYER_LIST = 'SET_LAYER_LIST';

export const GET_ACTIVE_LAYER_TAB = 'GET_ACTIVE_LAYER_TAB';
export const SET_ACTIVE_LAYER_TAB = 'SET_ACTIVE_LAYER_TAB';

export const GET_ACTIVE_LAYERS = 'GET_ACTIVE_LAYERS';
export const SET_ACTIVE_LAYERS = 'SET_ACTIVE_LAYERS';
export const GET_ACTIVE_LAYERS_FULFILLED = 'GET_ACTIVE_LAYERS_FULFILLED';

// Map config
export const GET_MAP_CONFIG = 'GET_MAP_CONFIG';
export const GET_MAP_CONFIG_FULFILLED = 'GET_MAP_CONFIG_FULFILLED';

// Table
export const TOGGLE_TABLE = 'TOGGLE_TABLE';
export const TOGGLE_FILTER = 'TOGGLE_FILTER';

export const GET_FEATURES_FULFILLED = 'GET_FEATURES_FULFILLED';
export const GET_FEATURES = 'GET_FEATURES';
export const SELECT_FEATURES = 'SELECT_FEATURES';
export const SET_FEATURES = 'SET_FEATURES';

// Search
export const GET_SEARCH_LAYERS = 'GET_SEARCH_LAYERS';
export const GET_SEARCH_LAYERS_FULFILLED = 'GET_SEARCH_LAYERS_FULFILLED';
export const SET_SEARCH_FETCHING = 'SET_SEARCH_FETCHING';
export const SEARCH_FEATURES_FULFILLED = 'SEARCH_FEATURES_FULFILLED';

export const SET_SEARCH_STATE = 'SET_SEARCH_STATE';
export const SET_SEARCH_OPTIONS = 'SET_SEARCH_OPTIONS';
